# Generated by Django 3.0 on 2021-05-16 16:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('trd_share_quantity', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ticker', models.CharField(choices=[('TCS', 'Tata Consultancy Services Limited'), ('WIPRO', 'Wipro Limited'), ('GODREJIND', 'Godrej Industries Ltd')], max_length=100)),
                ('category', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=20)),
                ('shareholder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(choices=[('TCS', 'Tata Consultancy Services Limited'), ('WIPRO', 'Wipro Limited'), ('GODREJIND', 'Godrej Industries Ltd')], max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('avg_buy_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('share_quantity', models.PositiveIntegerField()),
                ('shareholder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
